### PR TITLE
Reorganization of the Database downloading and the fixing #63

### LINKED ISSUE #7: Put configs in YAML/JSON format
Having configurations in a dedicated file format (not .py) makes more sense, as it can be more conveniently placed in different locations.

### LINKED ISSUE #63: Currently CHEBI is being downloaded everytime you start the program.
https://github.com/Porthmeus/MeMoMe/blob/656b94632b6603512e871469dae88929e3aaf452/src/annotateBulkRoutines.py#L28

Please remove this and add it to the databases.
Reasoning: Users will assume that this program runs without the internet and IMHO it should. Thus the current solution is not appropriate

### PR DESCRIPTION
**Pull request by Porthmeus**
fixes #63
fixes #7 
Change log:
Introduced a config.yml file to configure database download and to introduce a facility to configure other global parameters 
fixed #63 - chebi database is now also downloaded once and that accessed as needed
downloading functions were adjusted to work with the new config.yml file
removed the unit tests for the download functions, as these have become obsolete
Ignoring synchronization of the Database directory
Added the figure for the general concept of MeMoMe in the concept directory

### CODE REVIEW

**Review by Unaimend — COMMENTED** [review]
Nice

**Review by Unaimend — APPROVED** [review]

**Comment by Unaimend** [comment]
image

**Comment by Unaimend** [comment]
But it works for Stefano, so no idea whats wrong

**Comment by Unaimend** [comment]
image
Removing anconda from the channels makes most errors disappear

**Comment by Porthmeus** [comment]
This is the problem with **not** manually curating the requirements file... I have no idea what is happening, but might be very specific to either your or my system. Lets discuss after Christmas, how to handle the requirements file in the future.

**Pull request merged**
